{ pkgs, ... }:

{
  enable = true;
  settings = {
    theme = "catppuccin_mocha";
    editor = {
      bufferline = "multiple";
      "color-modes" = true;
      cursorline = true;
      "line-number" = "relative";
      "completion-timeout" = 5;
      "true-color" = true;
      "cursor-shape" = {
        insert = "bar";
        normal = "block";
        select = "underline";
      };
      "indent-guides" = {
        render = true;
      };
      statusline = {
        left = [ "mode" "file-name" "read-only-indicator" "file-modification-indicator" ];
        center = [ ];
        right = [ "diagnostics" "spinner" "selections" "register" "position" "file-encoding" ];
        mode = {
          normal = "π";
          insert = "ι";
          select = "ν";
        };
      };
      "file-picker" = {
        hidden = false;
      };
    };
    keys = {
      normal = {
        esc = [ "collapse_selection" "keep_primary_selection" ];
        tab = "goto_next_function";
        "S-tab" = "goto_prev_function";
        "C-y" = ":yank-diagnostic";
        "C-s" = ":w";
        X = "extend_line_above";
        "C-q" = ":q";
        "A-q" = ":q!";
        "C-w" = {
          c = ":bc";
        };
      };
      insert = {
        "C-c" = "yank_to_clipboard";
        "C-del" = [ "move_next_word_start" "delete_selection" ];
        "C-o" = [ "open_above" ];
        "C-p" = [ "paste_before" ];
        "C-s" = [ "normal_mode" ":w" ];
        "C-space" = [ "completion" ];
        "C-v" = [ "paste_clipboard_before" ];
        "C-u" = [ "undo" ];
        "A-u" = [ "redo" ];
        "A-c" = [ ":config-open" ];
        "C-e" = [ "move_next_word_start" ];
        "A-e" = [ "move_next_long_word_start" ];
        "C-y" = [ "yank" ];
        "C-w" = [ "move_next_word_end" "move_prev_word_end" "move_next_word_end" ];
        "A-w" = [ "move_next_long_word_end" "move_prev_long_word_start" "move_next_long_word_end" ];
        "C-left" = [ "move_prev_word_start" ];
        "C-right" = [ "move_next_word_end" ];
        "C-up" = [ "extend_to_line_bounds" "delete_selection" "move_line_up" "paste_before" "move_line_up" ];
        "C-down" = [ "extend_to_line_bounds" "delete_selection" "paste_after" "move_line_down" ];
        up = "no_op";
        down = "no_op";
        left = "no_op";
        right = "no_op";
        pageup = "no_op";
        pagedown = "no_op";
        home = "no_op";
        end = "no_op";
      };
      select = {
        esc = [ "collapse_selection" "keep_primary_selection" "normal_mode" ];
      };
    };
  };
  themes = {
    catppuccin_mocha = {
      "attribute" = "yellow";
      "type" = "yellow";
      "type.enum.variant" = "teal";
      "constructor" = "sapphire";
      "constant" = "peach";
      "constant.character" = "teal";
      "constant.character.escape" = "pink";
      "string" = "green";
      "string.regexp" = "pink";
      "string.special" = "blue";
      "string.special.symbol" = "red";
      "comment" = { fg = "overlay2"; modifiers = [ "italic" ]; };
      "variable" = "text";
      "variable.parameter" = { fg = "maroon"; modifiers = [ "italic" ]; };
      "variable.builtin" = "red";
      "variable.other.member" = "blue";
      "label" = "sapphire";
      "punctuation" = "overlay2";
      "punctuation.special" = "sky";
      "keyword" = "mauve";
      "keyword.control.conditional" = { fg = "mauve"; modifiers = [ "italic" ]; };
      "operator" = "sky";
      "function" = "blue";
      "function.macro" = "rosewater";
      "tag" = "blue";
      "namespace" = { fg = "yellow"; modifiers = [ "italic" ]; };
      "special" = "blue";
      "markup.heading.1" = "red";
      "markup.heading.2" = "peach";
      "markup.heading.3" = "yellow";
      "markup.heading.4" = "green";
      "markup.heading.5" = "sapphire";
      "markup.heading.6" = "lavender";
      "markup.list" = "teal";
      "markup.list.unchecked" = "overlay2";
      "markup.list.checked" = "green";
      "markup.bold" = { fg = "red"; modifiers = [ "bold" ]; };
      "markup.italic" = { fg = "red"; modifiers = [ "italic" ]; };
      "markup.link.url" = { fg = "blue"; modifiers = [ "italic" "underlined" ]; };
      "markup.link.text" = "lavender";
      "markup.link.label" = "sapphire";
      "markup.raw" = "green";
      "markup.quote" = "pink";
      "diff.plus" = "green";
      "diff.minus" = "red";
      "diff.delta" = "blue";
      "ui.background" = { fg = "text"; bg = "base"; };
      "ui.linenr" = { fg = "surface1"; };
      "ui.linenr.selected" = { fg = "lavender"; };
      "ui.statusline" = { fg = "subtext1"; bg = "mantle"; };
      "ui.statusline.inactive" = { fg = "surface2"; bg = "mantle"; };
      "ui.statusline.normal" = { fg = "base"; bg = "rosewater"; modifiers = [ "bold" ]; };
      "ui.statusline.insert" = { fg = "base"; bg = "green"; modifiers = [ "bold" ]; };
      "ui.statusline.select" = { fg = "base"; bg = "lavender"; modifiers = [ "bold" ]; };
      "ui.popup" = { fg = "text"; bg = "surface0"; };
      "ui.window" = { fg = "crust"; };
      "ui.help" = { fg = "overlay2"; bg = "surface0"; };
      "ui.bufferline" = { fg = "subtext0"; bg = "mantle"; };
      "ui.bufferline.active" = { fg = "mauve"; bg = "base"; underline = { color = "mauve"; style = "line"; }; };
      "ui.bufferline.background" = { bg = "crust"; };
      "ui.text" = "text";
      "ui.text.focus" = { fg = "text"; bg = "surface0"; modifiers = [ "bold" ]; };
      "ui.text.inactive" = { fg = "overlay1"; };
      "ui.text.directory" = { fg = "blue"; };
      "ui.virtual" = "overlay0";
      "ui.virtual.ruler" = { bg = "surface0"; };
      "ui.virtual.indent-guide" = "surface0";
      "ui.virtual.inlay-hint" = { fg = "surface1"; bg = "mantle"; };
      "ui.virtual.jump-label" = { fg = "rosewater"; modifiers = [ "bold" ]; };
      "ui.selection" = { bg = "surface1"; };
      "ui.cursor" = { fg = "base"; bg = "secondary_cursor"; };
      "ui.cursor.primary" = { fg = "base"; bg = "rosewater"; };
      "ui.cursor.match" = { fg = "peach"; modifiers = [ "bold" ]; };
      "ui.cursor.primary.normal" = { fg = "base"; bg = "rosewater"; };
      "ui.cursor.primary.insert" = { fg = "base"; bg = "green"; };
      "ui.cursor.primary.select" = { fg = "base"; bg = "lavender"; };
      "ui.cursor.normal" = { fg = "base"; bg = "secondary_cursor_normal"; };
      "ui.cursor.insert" = { fg = "base"; bg = "secondary_cursor_insert"; };
      "ui.cursor.select" = { fg = "base"; bg = "secondary_cursor_select"; };
      "ui.cursorline.primary" = { bg = "cursorline"; };
      "ui.highlight" = { bg = "surface1"; modifiers = [ "bold" ]; };
      "ui.menu" = { fg = "overlay2"; bg = "surface0"; };
      "ui.menu.selected" = { fg = "text"; bg = "surface1"; modifiers = [ "bold" ]; };
      "diagnostic.error" = { underline = { color = "red"; style = "curl"; }; };
      "diagnostic.warning" = { underline = { color = "yellow"; style = "curl"; }; };
      "diagnostic.info" = { underline = { color = "sky"; style = "curl"; }; };
      "diagnostic.hint" = { underline = { color = "teal"; style = "curl"; }; };
      "diagnostic.unnecessary" = { modifiers = [ "dim" ]; };
      error = "red";
      warning = "yellow";
      info = "sky";
      hint = "teal";
      palette = {
        rosewater = "#f5e0dc";
        flamingo = "#f2cdcd";
        pink = "#f5c2e7";
        mauve = "#cba6f7";
        red = "#f38ba8";
        maroon = "#eba0ac";
        peach = "#fab387";
        yellow = "#f9e2af";
        green = "#a6e3a1";
        teal = "#94e2d5";
        sky = "#89dceb";
        sapphire = "#74c7ec";
        blue = "#89b4fa";
        lavender = "#b4befe";
        text = "#cdd6f4";
        subtext1 = "#bac2de";
        subtext0 = "#a6adc8";
        overlay2 = "#9399b2";
        overlay1 = "#7f849c";
        overlay0 = "#6c7086";
        surface2 = "#585b70";
        surface1 = "#45475a";
        surface0 = "#313244";
        base = "#1e1e2e";
        mantle = "#181825";
        crust = "#11111b";
        cursorline = "#2a2b3c";
        secondary_cursor = "#b5a6a8";
        secondary_cursor_select = "#878ec0";
        secondary_cursor_normal = "#b5a6a8";
        secondary_cursor_insert = "#7ea87f";
      };
    };
  };
}
