[agents]
cloud_conversation_storage_enabled = false

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.input]
nld_in_terminal_enabled = false
show_agent_tips = false
ai_auto_detection_enabled = false

[agents.warp_agent.other]
agent_attribution_enabled = false
should_show_oz_updates_in_zero_state = false
should_render_use_agent_toolbar_for_user_commands = false

[agents.warp_agent.active_ai]
rule_suggestions_enabled = false

[agents.voice]
voice_input_enabled = false

[agents.third_party]
should_render_cli_agent_toolbar = false

[agents.third_party.cli_agent_toolbar_chip_selection_setting]

[agents.third_party.cli_agent_toolbar_chip_selection_setting.custom]
left = ["file_attach", "file_explorer"]
right = [{ context_chip = "date" }, { context_chip = "time_12" }]

[agents.knowledge]
rules_enabled = false
warp_drive_context_enabled = false

[agents.execution_profiles]

[agents.execution_profiles.default]
apply_code_diffs = "agent_decides"
ask_user_question = "always_ask"
autosync_plans_to_warp_drive = true
command_allowlist = []
command_denylist = [
  'bash(\s.*)?',
  'fish(\s.*)?',
  'pwsh(\s.*)?',
  'sh(\s.*)?',
  'zsh(\s.*)?',
  'curl(\s.*)?',
  'eval(\s.*)?',
  'exec(\s.*)?',
  'source(\s.*)?',
  'wget(\s.*)?',
  'dig(\s.*)?',
  'nslookup(\s.*)?',
  'host(\s.*)?',
  'ssh(\s.*)?',
  'scp(\s.*)?',
  'rsync(\s.*)?',
  'telnet(\s.*)?',
  'rm(\s.*)?',
]
computer_use = "never"
directory_allowlist = []
execute_commands = "always_ask"
mcp_allowlist = []
mcp_denylist = []
mcp_permissions = "agent_decides"
name = "Default"
read_files = "agent_decides"
run_agents = "always_ask"
web_search_enabled = true
write_to_pty = "always_ask"

[account]
is_settings_sync_enabled = true

[privacy]
crash_reporting_enabled = false
telemetry_enabled = false

[text_editing]

[appearance]
spacing = "normal"

[appearance.input]
input_mode = "pinned_to_bottom"

[appearance.themes]
system_theme = true
selected_system_themes = {
  dark = { custom = { name = "Catppuccin Mocha", path = "catppuccin_mocha.yml" } },
  light = { custom = { name = "Catppuccin Latte", path = "catppuccin_latte.yml" } },
}

[appearance.text]
notebook_font_size = 14.0
font_size = 24.0
font_name = "Iosevka Nerd Font Mono"
ai_font_name = "Iosevka Nerd Font Mono"
match_ai_font = true
ligature_rendering_enabled = true

[appearance.vertical_tabs]
enabled = true
display_granularity = "panes"
primary_info = "working_directory"
compact_subtitle = "branch"
show_details_on_hover = true
view_mode = "compact"
hide_title_bar_search_bar = true
show_panel_in_restored_windows = true

[appearance.window]
zoom_level = 80
left_panel_visibility_across_tabs = true
override_opacity = 100
override_blur = 64

[appearance.icon]
app_icon = "aurora"
show_dock_icon = true

[appearance.tabs]
directory_tab_colors = { "/Users/spicyz/Documents/work" = "suppressed" }
workspace_decoration_visibility = "on_hover"

[appearance.full_screen_apps]
alt_screen_padding = { custom = { uniform_padding = 32.0 } }

[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[terminal]
maximum_grid_size = 100000
copy_on_select = false
show_terminal_zero_state_block = false
use_audible_bell = true
osc52_clipboard_access = "write_only"

[terminal.input]
input_box_type_setting = "classic"
honor_ps1 = true
show_hint_text = false
at_context_menu_in_terminal_mode = false
outline_codebase_symbols_for_at_context_menu = false

[general]
default_tab_config_path = "/Users/spicyz/.warp/tab_configs/startup_config.toml"
login_item = false
show_changelog_after_update = false
quit_on_last_window_closed = true
snackbar_enabled = false
default_session_mode = "tab_config"
show_warning_before_quitting = true

[warp_drive]
enabled = false

[code]

[code.indexing]
agent_mode_codebase_context = false

[code.editor]
prefer_tabbed_editor_view = true
prefer_markdown_viewer = true
